[General]
key_pmi=6520974734
key_pmi_invite_msg="Rahul G is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Rahul G's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://us05web.zoom.us/j/6520974734?pwd=T0hLRHM1TUNyMDRUbWI2VjM4S1lRdz09\r\n\r\nMeeting ID: 652 097 4734\r\nPasscode: xM6u0B\r\n\r\n"
